register/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.contrib.auth import views as authviews

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^table-records$', views.table_records, name='table'),
    url(r'^logout/$', authviews.logout, {"next_page": '/'}, name="logout"), 
    url(r'^auth-token/(?P<token>\w+)/$',views.authenticate_token,name="auth-token"),
    url(r'^records/ajax-records-date$',views.ajax_records_date,name="ajax-records-date"),
    url(r'^cache-error$', views.error_cache, name='error-cache'),
]

signin/urls.py
from django.contrib import admin
from signin import settings
from team_signin.views import Events
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib.auth import views as authviews

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^events/', Events.as_view()), 
    url(r'^',include(('register.urls','register'),namespace="register")),
    url(r'^slack/', include('django_slack_oauth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/sign-in-bot/authenticate.html
{% load static bootstrap4 %}
<html>
    <head>
        <title>authenticate</title>
        {% block styles %}
        {% endblock %}
    </head>
    <body>
        {% block content %}
        
            <h1>Username: {{user.slackprofile.username}}</h1>
            <h1>status: {{warn}}</h1>

        {% endblock %}
        {% block script %}
        {% endblock %}

    </body>
</html>

templates/sign-in-bot/index.html
{% extends "base/base_sign-in-bot.html" %}
{% load static %}
<head>
        {% block head %}
        {{ block.super }}
        {% endblock %}
        {% block styles %}
        {{ block.super }}
        {% endblock %}
</head>

<body>
        {% block content %}
        {{ block.super }}

                    <!-- start welcome section-->
                    <section class="welcome p-t-10">
                            <div class="container">
                                <div class="row">
                                    <div class="col-md-12">
                                        <h1 class="title-4">Welcome
                                            <span>{{user.slackprofile.username}}</span>
                                        </h1>
                                        <hr class="line-seprate">
                                    </div>
                                </div>
                            </div>
                    </section>
                    <!-- stop welcome section-->

                    <!-- STATISTIC-->
                    <section class="statistic statistic2">
                            <div class="container">
                                <div class="card text-center">
                                    <div class="card-header">
                                        Today's record
                                    </div>
                                    <div class="card-body">
                                        <h4 class="card-title">Token Info</h4>
                                        {% if day_record %}
                                        <p class="card-text">Your Token: {{day_record.token}}</p>
                                        <p class="card-text">Date: {{day_record.date_in }}</p>
                                        <p class="card-text">Time in: {{ day_record.time_description }} </p>
                                        <p class="card-text">Authenticated: {% if day_record.is_authenticated %} Yes {% else %} No {% endif %}</p>
                                        {% if not day_record.is_authenticated %}
                                        <a href="{% url 'register:auth-token' day_record.token %}" class="btn btn-primary">click here to authenticate </a>
                                        {% endif %}
                                        {% else %}
                                        <p class="card-text">You have no token yet please request one via the slack bot</p>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </section>
                        <!-- END STATISTIC-->
        {% endblock %}

</body>
  

templates/sign-in-bot/roll_table.html
{% extends "base/base_sign-in-bot.html" %}
{% load static %}
<head>
        {% block head %}
        {{ block.super }}
        {% endblock %}
        {% block styles %}
        {{ block.super }}
      
        {% endblock %}
</head>

<body>
        {% block content %}
        {{ block.super }}
                    <!-- start welcome section-->
                    <section class="welcome p-t-10">
                            <div class="container">
                                <div class="row">
                                    <div class="col-md-12">
                                        <h1 class="title-4">Welcome
                                            <span>{{user.slackprofile.username}}</span>
                                        </h1>
                                        <hr class="line-seprate">
                                    </div>
                                </div>
                            </div>
                    </section>
                    <!-- stop welcome section-->
          



          <!-- DATA TABLE-->
          <section class="p-t-20">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1 class="title-5 m-b-35">Roll Call</h1>
                            <div class="table-data__tool">
                                <form class="form-inline" id="filter-date">
                                    {% csrf_token %}
                                        <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                                                <input class="form-control" type="date" id="date-input" required>
                                        </div>
                                        <button id="filter-date" type="submit" class="btn btn-primary">Filter</button>
                                </form>
                            </div>
                            <div>
                                <h4>Will add more filtering options e.g class name or department when i get time to work on this</h4>
                            </div>
                            <div class="table-responsive table-responsive-data2">
                                <table class="table table-data2">
                                    <thead>
                                        <tr>
                                            {% if table_headers %}
                                            {% for heading in table_headers %}
                                                <th> {{ heading }} </th>
                                            {% endfor %}
                                            {% endif %}
                                        </tr>
                                    </thead>
                                    <tbody id="rec-items">
                                        {% if records %}
                                        {% for entry in records %}
                                        <tr class="tr-shadow">
                                            <td>{{ entry.profile.username }}</td>
                                            <td>{{ entry.profile.user.email }}</td>
                                            <td>{{ entry.time_description }}</td>
                                        </tr>
                                        <tr class="spacer"></tr>
                                        {% endfor %}
                                        {% endif %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- END DATA TABLE-->

        {% endblock %}

        {% block script %}
        {{ block.super }}
        {% endblock %}

</body>
  